CREATE TABLE job_listings (
  id UUID PRIMARY KEY,
  city TEXT,
  company TEXT,
  currency TEXT,
  description TEXT,
  experience TEXT,
  experience_max INTEGER,
  experience_min INTEGER,
  expires_at TIMESTAMP,
  external_link TEXT,
  has_equity BOOLEAN,
  industries JSONB,
  is_boosted BOOLEAN,
  is_remote BOOLEAN,
  is_salary_visible BOOLEAN,
  job_skills JSONB,
  job_type TEXT,
  position TEXT,
  published_at TIMESTAMP,
  salary_avg INTEGER,
  salary_max INTEGER,
  salary_min INTEGER,
  starts_featuring_at TIMESTAMP,
  taxonomies JSONB,
  title TEXT,
  vacancy_count INTEGER
);